// Originally generated by FlutterFire CLI, then reworked to read every value
// from compile-time --dart-define config (see AppEnv) so no secret ships as a
// readable asset inside the APK.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'core/config/app_env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: AppEnv.firebaseApiKey,
    appId: AppEnv.firebaseAppIdWeb,
    messagingSenderId: AppEnv.firebaseMessagingSenderId,
    projectId: AppEnv.firebaseProjectId,
    authDomain: AppEnv.firebaseAuthDomain,
    storageBucket: AppEnv.firebaseStorageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: AppEnv.firebaseApiKey,
    appId: AppEnv.firebaseAppIdAndroid,
    messagingSenderId: AppEnv.firebaseMessagingSenderId,
    projectId: AppEnv.firebaseProjectId,
    storageBucket: AppEnv.firebaseStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: AppEnv.firebaseApiKey,
    appId: AppEnv.firebaseAppIdIos,
    messagingSenderId: AppEnv.firebaseMessagingSenderId,
    projectId: AppEnv.firebaseProjectId,
    authDomain: AppEnv.firebaseAuthDomain,
    storageBucket: AppEnv.firebaseStorageBucket,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: AppEnv.firebaseApiKey,
    appId: AppEnv.firebaseAppIdMacos,
    messagingSenderId: AppEnv.firebaseMessagingSenderId,
    projectId: AppEnv.firebaseProjectId,
    authDomain: AppEnv.firebaseAuthDomain,
    storageBucket: AppEnv.firebaseStorageBucket,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: AppEnv.firebaseApiKey,
    appId: AppEnv.firebaseAppIdWindows,
    messagingSenderId: AppEnv.firebaseMessagingSenderId,
    projectId: AppEnv.firebaseProjectId,
    authDomain: AppEnv.firebaseAuthDomain,
    storageBucket: AppEnv.firebaseStorageBucket,
  );
}
